# The webhook runs in "scf" namespace
# Looking for pods running in "scf-eirini"
---
apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      creationTimestamp: null
      name: "eirini-helloworld-extension"
    rules:
    - apiGroups:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: "eirini-helloworld-extension"
      namespace: "scf"
    roleRef:
      kind: ClusterRole
      name: "eirini-helloworld-extension"
      apiGroup: rbac.authorization.k8s.io
    subjects:
    - kind: ServiceAccount
      name: "eirini-helloworld-extension"
      namespace: "scf"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "eirini-helloworld-extension"
  namespace: scf
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eirini-helloworld-extension
  namespace: scf
subjects:
- kind: ServiceAccount
  name: eirini-helloworld-extension
roleRef:
  kind: Role
  name: eirini-helloworld-extension
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: eirini-helloworld-extension
  namespace: scf
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  verbs:
    - '*'
---
apiVersion: v1
kind: Service
metadata:
  name: eirini-helloworld-extension-service
  namespace: scf
spec:
  selector:
    app: eirini-helloworld-extension
  ports:
  - protocol: TCP
    port: 443
    targetPort: 4545
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eirini-helloworld-extension
  namespace: scf
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eirini-helloworld-extension
    spec:
      serviceAccountName: "eirini-helloworld-extension"
      containers:
      - image: drnic/eirinix-helloworld:latest
        name: eirini-helloworld-extension
        imagePullPolicy: IfNotPresent
        env:
        - name: WEBHOOK_SERVICE_NAME
          value: eirini-helloworld-extension-service
        - name: WEBHOOK_NAMESPACE
          value: scf
        - name: POD_NAMESPACE
          value: scf-eirini
      restartPolicy: Always
